# Generated by Django 3.2.16 on 2023-01-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_cuisineries', '0002_alter_membre_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='prenom',
        ),
    ]
