# Generated by Django 3.2.16 on 2023-01-05 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_cuisineries', '0003_auto_20230105_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='role',
        ),
        migrations.AlterField(
            model_name='membre',
            name='referent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='referent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
