# Generated by Django 3.2.16 on 2023-01-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cuisineries', '0004_auto_20230105_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='competences',
            field=models.JSONField(null=True),
        ),
    ]
